import { useEffect, useState } from 'react'
import { View, Text, Input, Picker, ScrollView } from '@tarojs/components'
import Taro from '@tarojs/taro'
import { ArrowLeft } from '@nutui/icons-react-taro'
import { getTeacherCoachingQuotas, createTeacherCoachingAppointment, type TeacherCoachingQuotaRow } from '../../api/coaching'
import { color } from '../../styles/tokens'
import './index.scss'

function today() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}` }
function label(row: TeacherCoachingQuotaRow) { return row.student?.displayName || row.student?.username || row.student?.email || `学员 #${row.studentId}` }
export default function CreateCoachingAppointment() {
  const [students, setStudents] = useState<TeacherCoachingQuotaRow[]>([]); const [studentIndex, setStudentIndex] = useState(0); const [date, setDate] = useState(today()); const [startTime, setStartTime] = useState('19:00'); const [endTime, setEndTime] = useState('20:00'); const [title, setTitle] = useState('英语陪练'); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  useEffect(() => { void getTeacherCoachingQuotas({ limit: 100, includeSelf: true }).then((res) => { const data: any = res.data; setStudents(Array.isArray(data?.list) ? data.list : Array.isArray(data) ? data : []); setLoading(false) }, () => { Taro.showToast({ title: '学员加载失败', icon: 'none' }); setLoading(false) }) }, [])
  const submit = async () => { const student = students[studentIndex]; if (!student) { Taro.showToast({ title: '请先添加学员', icon: 'none' }); return } if (!date || !startTime || !endTime) { Taro.showToast({ title: '请完善时间', icon: 'none' }); return } setSaving(true); try { const res = await createTeacherCoachingAppointment({ studentId: student.studentId, scheduledDate: date, startTime, endTime, title: title.trim() || '英语陪练' }); if (res.code !== 200) { Taro.showToast({ title: res.msg || '创建失败', icon: 'none' }); return } Taro.showToast({ title: '预约成功', icon: 'success' }); setTimeout(() => Taro.navigateBack(), 600) } catch { Taro.showToast({ title: '创建失败', icon: 'none' }) } finally { setSaving(false) } }
  return <View className="create-appointment"><View className="ca__nav"><View className="ca__back" onClick={() => Taro.navigateBack()}><ArrowLeft size={22} color={color.charcoal} /></View><Text className="ca__title">创建陪练预约</Text><View className="ca__back" /></View><ScrollView className="ca__body" scrollY enableFlex><View className="ca__card">{loading ? <Text className="ca__loading">加载学员中...</Text> : <><Text className="ca__label">学员 *</Text><Picker mode="selector" range={students.map(label)} value={studentIndex} onChange={(e) => setStudentIndex(Number(e.detail.value))}><View className="ca__picker"><Text>{students.length ? label(students[studentIndex]) : '暂无学员'}</Text><Text>选择</Text></View></Picker></>}<Text className="ca__label">日期 *</Text><Picker mode="date" value={date} start={today()} onChange={(e) => setDate(e.detail.value)}><View className="ca__picker"><Text>{date}</Text><Text>选择日期</Text></View></Picker><Text className="ca__label">开始时间 *</Text><Picker mode="time" value={startTime} onChange={(e) => setStartTime(e.detail.value)}><View className="ca__picker"><Text>{startTime}</Text><Text>选择时间</Text></View></Picker><Text className="ca__label">结束时间 *</Text><Picker mode="time" value={endTime} onChange={(e) => setEndTime(e.detail.value)}><View className="ca__picker"><Text>{endTime}</Text><Text>选择时间</Text></View></Picker><Text className="ca__label">预约标题</Text><Input className="ca__input" value={title} onInput={(e) => setTitle(e.detail.value)} placeholder="英语陪练" /><View className={`ca__submit ${saving ? 'ca__submit--disabled' : ''}`} onClick={() => void submit()}><Text>{saving ? '创建中...' : '创建预约'}</Text></View></View></ScrollView></View>
}
